### PR TITLE
Fix issue #6

### PR DESCRIPTION
**Pull request by asiripanich**

### CODE REVIEW

**Comment by asiripanich** [comment]
@raisin-toast could you please review this PR? Thanks.

**Comment by raisin-toast** [comment]
The household id is different for the general release - it is `"hhrhid"`

**Comment by asiripanich** [comment]
> The household id is different for the general release - it is `"hhrhid"`

Do you think we should add `hhrhid` the list of default variables of `hil_fetch()`? 

https://github.com/asiripanich/hildar/blob/7d9ef3a287ff471a7ea4e2e9209cc0e99e90bd96/R/fetch.R#L98-L109

I'm thinking of implement #9 to make the default variables customisable.

**Comment by raisin-toast** [comment]
Yeah implementing #9 would work. I think the issue in the short term is that I get an error every time because `hhid` isn't in the general release.

**Comment by asiripanich** [comment]
@raisin-toast could you review it again please. I just implemented #9.

```
#' To edit both files, you can use [usethis::edit_r_profile()] and [usethis::edit_r_environ()].
#'
#' For `.Renviron`, please make sure `HILDAR_USER_DEFAULT_VARS` has the following format:
#'
#' ```
#' HILDAR_USER_DEFAULT_VARS="hhid, losat"
#' ```
#'
#' For `.Rprofile`, please make sure `HILDAR_USER_DEFAULT_VARS` has the following format:
#'
#' ```
#' options(HILDAR_USER_DEFAULT_VARS = c("hhid", "losat"))
#' ```
#'
#' The main advantage of setting the variables in your `.Renviron` file is
#' that all your new R sessions that don't have a project-specific `.Rprofile`
#' file will use the `HILDAR_USER_DEFAULT_VARS` from your `.Renviron` file.
```

**Pull request merged**
